services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend/prisma:/app/prisma
      - sqlite_data:/app/prisma
    depends_on: []

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

volumes:
  sqlite_data:
